spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  profiles:
    active: default

logging:
  level:
    com:
      adrian:
        recipe: debug